# -*- coding: utf-8 -*-
"""3_knn,py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S72_03ZVJ2MjofoWslbvjP2zthR5_eDs
"""

# Hand-written digits using KNN algorithm

import pandas as pd
from sklearn.datasets import load_digits               # Built-in digits dataset
from sklearn.model_selection import train_test_split   # To split dataset
from sklearn.neighbors import KNeighborsClassifier     # KNN model
from sklearn.metrics import accuracy_score             # To evaluate performance

# Load the digits dataset
digits = load_digits()

# Convert to pandas DataFrame
df = pd.DataFrame(data=digits.data)                    # Features
df['target'] = digits.target                           # Labels

# Display first 5 rows
print("Sample Data Preview:")
print(df.head())

# Separate features and target
X = df.drop('target', axis=1)                          # Feature matrix
Y = df['target']                                       # Target labels

# Split into train and test sets (60% test)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.6, random_state=87)

# Train the KNN classifier (k=5)
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = model.predict(X_test)

# Evaluate the performance
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy of KNN on Digits dataset:", accuracy)

