# -*- coding: utf-8 -*-
"""4_svm.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yp2RLiRuXxJ8PsMNg-exKTCPKOGMslNu
"""

#SVM for Breast Cancer datasets
import pandas as pd
from sklearn.datasets import load_breast_cancer             #InBuilt cancer dataset
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC                                 #SVM classifier
from sklearn.metrics import accuracy_score

#Breast Cancer dataset
data = load_breast_cancer()

# Convert to DataFrame
df = pd.DataFrame(data.data, columns=data.feature_names)    # Features
df['target'] = data.target                                  # Labels

# Display first 5 rows
print("Sample Data Preview:")
print(df.head())

# Separate features and labels
X = df.drop('target', axis=1)
Y = df['target']

# Split into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=12)

# SVM model (linear kernel)
model = SVC(kernel='linear')
model.fit(X_train, Y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy of SVM on Breast Cancer dataset:", accuracy)

