# -*- coding: utf-8 -*-
"""5_random_forest.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-IP9ShLF62RV5cY-vVBMtkSYIsh0cud0
"""

# Random Forest for Wine dataset

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_wine                         # Inbuilt wine dataset
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier            # Random Forest model
from sklearn.metrics import accuracy_score

# Load Wine Dataset
data = load_wine()

# Convert to DataFrame
df = pd.DataFrame(data.data, columns=data.feature_names)      # Features
df['target'] = data.target                                    # Target

# First 5 rows
print("Sample Data")
print(df.head())

# Separate Feature and Target
X = df.drop('target', axis=1)
y = df['target']

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=32)

# Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=32)
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of Random Forest on Wine dataset:", accuracy)

#bar
plt.figure(figsize=(6, 4))
sns.countplot(x=y_pred, palette='Set2')
plt.title('Predicted Class Distribution - Wine Dataset')
plt.xlabel('Wine Class')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1, 2], labels=data.target_names)
plt.tight_layout()
plt.show()

